version: "3.8"

services:
  fullstack:
    build:
      context: ../../
      dockerfile: Dockerfile
    volumes:
      - ../../:/home/devuser/workspace
      - ../../frontend/node_modules:/home/devuser/workspace/frontend/node_modules
    working_dir: /home/devuser/workspace
    ports:
      - "3000:3000"
      - "8000:8000"
    command: ["sleep", "infinity"]

volumes:
  node_modules:
